name: html5media
---
Transcoding:
  transcode_upload_method: ''
  transcode_relative_video_path_ftp: ''
  transcode_relative_video_path_base: ''
  transcode_relative_audio_path_ftp: ''
  transcode_relative_audio_path_base: ''
  transcode_api_key: ''
  # eg: https://app.heywatch.com/pings/something/someaccount
  #transcode_use_development_webhook: ''
