---
Name: html5transcoding
After: framework/routes#rootroutes
---
# voor pingbacks
Director:
  rules:
    'transcode-log//$Action/$ID/$OtherID': 'Transcode_Controller'

# voor OEMBEDS (NOT working yet...)
Director:
  rules:
    'video-media//$Action/$ID/$OtherID': 'Video_Controller'
    'audio-media//$Action/$ID/$OtherID': 'Audio_Controller'